# Generated by Django 2.2.4 on 2020-05-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200501_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image_of_person',
        ),
    ]
