# Generated by Django 2.2.4 on 2020-05-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_contact_image_of_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
    ]
