# Generated by Django 2.2.4 on 2020-05-03 12:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=20, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
