# Generated by Django 2.2.4 on 2020-05-03 14:53

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_posts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(validators=[pages.models.Posts.value_char_check]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=20, validators=[pages.models.Posts.value_char_check]),
        ),
    ]
