# Generated by Django 2.2.4 on 2020-05-06 07:54

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200503_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[pages.models.min_length_char])),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=20, validators=[pages.models.min_length_char]),
        ),
    ]
