# Generated by Django 2.2.4 on 2020-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200511_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='catagory',
            field=models.ManyToManyField(default=0, related_name='catagory', to='pages.Catagory'),
        ),
    ]
