# Generated by Django 2.2.4 on 2020-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_posts_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='catagory',
            field=models.ManyToManyField(default=0, to='pages.Catagory'),
        ),
    ]
